#!/bin/sh
grep argoFloats /home/yourName/erddap/logs/log.txt | grep flagKey | grep http | tail -1 | sed -e 's/.*flagKey=//' > /app/flagKey.new
if [ -s /app/flagKey.new ]
then
  mv /app/flagKey.new /app/flagKey
fi
